[build]
  publish = "public"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/?view=dashboard-public"
  status = 200
  force = true
  